server:
    port: 8080
    servlet:
        context-path: /api
    error:
        include-message: always
        include-binding-errors: always
        include-exception: false

spring:
    neo4j:
        uri: neo4j://localhost:7687
        authentication:
            username: neo4j
            password: mysupersecret