version: "3.8"

services:
  familia-neo4j:
    container_name: familia-neo4j
    image: neo4j:5.5.0-community
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
#      - ./neo4j/import:/import
#      - ./neo4j/logs:/logs
#      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/mysupersecret

  familia-mongo:
    container_name: familia-mongo
    image: mongo:6.0.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: familia
      MONGO_INITDB_ROOT_PASSWORD: familia
      MONGO_INITDB_DATABASE: familia
    volumes:
      #- ./mongodb/data:/data/db
      - ./mongodb/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  familia-mongo-express:
    container_name: familia-mongo-express
    image: mongo-express:latest
    restart: always
    depends_on:
      - familia-mongo
    ports:
      - 2701:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: familia-mongo
      ME_CONFIG_BASICAUTH_USERNAME: express-admin
      ME_CONFIG_BASICAUTH_PASSWORD: SuperSecret123!
      ME_CONFIG_MONGODB_ADMINUSERNAME: familia
      ME_CONFIG_MONGODB_ADMINPASSWORD: familia

#  familia-backend:
#    image: familia:latest
#    restart: always
#    ports:
#      - 8080:8080