version: "3.8"

networks:
  warchol:
    driver: bridge

services:
  warchol-neo4j:
    container_name: warchol-neo4j
    image: neo4j:5.5.0-community
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
#      - ./neo4j/import:/import
#      - ./neo4j/logs:/logs
#      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/mysupersecret
    networks:
      - warchol

  warchol-mongo:
    container_name: warchol-mongo
    image: mongo:6.0.5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: familia
      MONGO_INITDB_ROOT_PASSWORD: familia
      MONGO_INITDB_DATABASE: familia
    volumes:
      #- ./mongodb/data:/data/db
      - ./mongodb/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - warchol

  warchol-mongo-express:
    container_name: warchol-mongo-express
    image: mongo-express:latest
    restart: always
    depends_on:
      - warchol-mongo
    ports:
      - 2701:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: warchol-mongo
      ME_CONFIG_BASICAUTH_USERNAME: express-admin
      ME_CONFIG_BASICAUTH_PASSWORD: SuperSecret123!
      ME_CONFIG_MONGODB_ADMINUSERNAME: familia
      ME_CONFIG_MONGODB_ADMINPASSWORD: familia
    networks:
      - warchol

  warchol-backend:
    profiles:
      - prod
    container_name: warchol-backend
    image: warchol-backend:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - warchol

  warchol-frontend:
    profiles:
      - prod
    container_name: warchol-frontend
    image: warchol-frontend:latest
#    build:
#      context: ../frontend
    restart: always
    ports:
      - 3000:80
    networks:
      - warchol