server:
    port: 8080
    servlet:
        context-path: /api
    error:
        include-message: always
        include-binding-errors: always
        include-exception: false

spring:
    neo4j:
        uri: neo4j://warchol-neo4j:7687
        authentication:
            username: neo4j
            password: mysupersecret
    data:
        mongodb:
            host: warchol-mongo
            port: 27017
            authentication-database: familia
            database: familia
            username: backend
            password: supersecret
            auto-index-creation: true

springdoc:
    swagger-ui:
        path: /swagger.html

cors:
    allowed-origins: http://warchol.mnowicki.net

security:
    jwt:
        secretKey: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4MjgwMjY5NiwiaWF0IjoxNjgyODAyNjk2fQ.-y4PMPjhvmqksszs7QGKcyr2w8yy_rdqfIrYhwHfA0Q
        tokenPrefix: "Bearer "
        tokenExpiration: 604800 #one week
        refreshTokenExpiration: 0
