server:
    port: 8080
    servlet:
        context-path: /api
    error:
        include-message: always
        include-binding-errors: always
        include-exception: false

spring:
    neo4j:
        uri: neo4j://localhost:7687
        authentication:
            username: neo4j
            password: mysupersecret
    data:
        mongodb:
            host: localhost
            port: 27017
            authentication-database: familia
            database: familia
            username: backend
            password: supersecret
            auto-index-creation: true



springdoc:
    swagger-ui:
        path: /swagger.html